### ISSUE TITLE
Port to Flutter web?

### ISSUE THREAD

**Issue by devanflores** [xainag/xain-mobile-voice-recognition#7]
How would I go about porting this to flutter web?

**Comment by biernacki** [comment]
@devanflores Providing support for flutter web for this example is unfortunately not possible without replacing large parts of the code responsible for audio capturing and for running our custom model. We are using here TensorFlow Lite to interpret the model, which is not available for browsers.

If you are interested in audio recognition on the web you could use TensorFlow.js. Here you'll find a good example from Google regarding voice recognition in the browser using tf.js - [Codelab](https://codelabs.developers.google.com/codelabs/tensorflowjs-audio-codelab/index.html) + [Github Repo](https://github.com/tensorflow/tfjs-models/tree/master/speech-commands).
